
name: Bash workflow

on: [push]

env:
  Team_name: Japan
  Team2_name: Germany

jobs:
  actions_demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pwd
    - run: chmod +x bash.sh
    - run: ./bash.sh


  env_vars_job:
    runs-on: ubuntu-latest
    env:
      name: Tomiyasu
    steps:
    - run: echo "Hello World"
    - run: echo "Hello $name" # name is the env var name, we access it with $var
    - run: echo "$Team_name beat $Team2_name:!!""
    - run: echo "${{secrets.Germany_Bribe_Amount}"