
name: Bash workflow

on: [push]
jobs:
  actions_demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pwd
    - run: chmod +x bash.sh
    - run: ./bash.sh
